Repository Vinicius-de-Morais/web-radio, pull requests merged in 2025-03, with the labels that each got.

#2 refactor: Create new Object module
  src/main.rs
  src/objects/mod.rs
  src/objects/radio.rs
  src/objects/station/mod.rs
  src/objects/station/station.rs
  src/objects/station/station_snapshot.rs
  src/objects/station/station_state.rs
  src/objects/subscriber.rs
  src/objects/track/mod.rs
  src/objects/track/track.rs
  src/objects/track/track_iterator.rs
  src/radio.rs
  tests/test.rs
Labels: t: refactor

#18 feat: Implementação do TrackIterator e correção do módulo principal
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/main.rs
  src/objects/track/track.rs
  src/objects/track/track_iterator.rs
  tests/test.rs
  tests/test_track_iterator.rs
Labels: t: feat

#22 fix: corrige uso de variáveis fora de escopo em new()
  src/objects/radio.rs
Labels: t: bugfix
